# Variables and gradients

## Variables

In [2]:
import torch
from torch.autograd import Variable

In [5]:
a = Variable(torch.ones(2,2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [6]:
# Not a variable
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
b = Variable(torch.ones(2,2), requires_grad=True)
print(a + b)
print(torch.add(a, b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [8]:
print(a * b)
print(torch.mul(a,b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


## Gradients



\begin{align}
\mathbf{y}_1 & = 5({x}_i+1)^2
\end{align}

In [12]:
x = Variable(torch.ones(2), requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [14]:
# Applying function to x

y = 5 * (x + 1) ** 2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

Backward should be called only on a scalar or with gradient w.r.t variable

In [20]:
o = (1/x.shape[0]) * torch.sum(y)
print(o)

tensor(20., grad_fn=<MulBackward0>)


In [21]:
o.backward()

In [22]:
print(x.grad)

tensor([10., 10.])


In [23]:
# Backward in detail
o.backward(torch.FloatTensor([1.0,1.0]))
x.grad

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.